import Head from "next/head"
import Image from "next/image"
import Header from "../components/Header"
import ManuallyConnectingHeader from "../components/ManuallyConnectingHeader"
import styles from "../styles/Home.module.css"

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Smart Contract lottery</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {/* <ManuallyConnectingHeader/> */}
            hello
        </div>
    )
}
